project_id = "fqhyfxdixqhouhrxaufb"

[functions.upload-to-ipfs]
verify_jwt = false

[functions.reset-tasks]
verify_jwt = false

[functions.create-badge-metadata]
verify_jwt = false

[functions.devnet-faucet]
verify_jwt = false

[functions.upload-metadata-to-ipfs]
verify_jwt = false

[functions.manage-quests]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false

[functions.remix-audio]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.verify-tweet]
verify_jwt = false

[functions.og-image]
verify_jwt = false
